# Generated by Django 5.2.16 on 2026-07-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Komitmen Kami untuk Udang Berkualitas Dunia', max_length=140)),
                ('body', models.TextField(default='Udang Emas Nusantara adalah unit usaha budidaya udang vaname modern di bawah CV Dua Satu Kreasi yang berlokasi di Muara Gembong, Kabupaten Bekasi. Kami menggabungkan pengalaman petambak, teknologi digital, dan manajemen budidaya berbasis data.')),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('vision', models.TextField(default='Menjadi perusahaan budidaya udang modern Indonesia yang terpercaya, berkelanjutan, dan berbasis teknologi untuk menghasilkan produk berkualitas dunia.')),
            ],
            options={
                'verbose_name': 'Tentang, Visi & Narasi',
                'verbose_name_plural': 'Tentang, Visi & Narasi',
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='facilities/')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Galeri Tambak',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PondStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Udang Emas Nusantara', max_length=120)),
                ('tagline', models.CharField(default='Dari Tambak Nusantara untuk Kualitas Dunia', max_length=180)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('hero_image', models.ImageField(blank=True, upload_to='hero/')),
                ('hero_badge', models.CharField(default='Tentang Kami', max_length=80)),
                ('hero_title_line_1', models.CharField(default='Dari Tambak Nusantara untuk', max_length=120)),
                ('hero_title_highlight', models.CharField(default='Kualitas Dunia', max_length=80)),
                ('hero_description', models.TextField(default='Udang berkualitas tinggi melalui budidaya modern, teknologi tepat guna, dan pengelolaan profesional yang berkelanjutan.')),
                ('primary_button_text', models.CharField(default='Kenali Kami Lebih Dekat', max_length=60)),
                ('primary_button_url', models.CharField(default='#tentang', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Contoh: 6281234567890', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(default='Muara Gembong, Kabupaten Bekasi', max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(default='Bersama kita wujudkan tambak Indonesia berkualitas dunia.', max_length=180)),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nama ikon Bootstrap Icons, mis. shield-check', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='landing.organizationrole')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
