# Generated by Django 5.2.16 on 2026-07-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_title', models.CharField(default='Tambak Kami dalam Angka', max_length=100)),
                ('values_title', models.CharField(default='Nilai-Nilai Kami', max_length=100)),
                ('organization_title', models.CharField(default='Struktur Organisasi', max_length=100)),
                ('organization_subtitle', models.CharField(default='Kolaborasi tim yang solid untuk budidaya udang berkualitas tinggi.', max_length=180)),
                ('facilities_title', models.CharField(default='Fasilitas Kami', max_length=100)),
                ('gallery_title', models.CharField(default='Galeri Tambak', max_length=100)),
            ],
            options={
                'verbose_name': 'Judul Bagian',
                'verbose_name_plural': '3. Judul Bagian',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Tentang, Visi & Narasi', 'verbose_name_plural': '2. Tentang, Visi & Narasi'},
        ),
        migrations.AlterModelOptions(
            name='companyvalue',
            options={'verbose_name': 'Nilai Perusahaan', 'verbose_name_plural': '7. Nilai Perusahaan'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Fasilitas', 'verbose_name_plural': '9. Fasilitas'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Keunggulan', 'verbose_name_plural': '4. Keunggulan'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Foto Galeri', 'verbose_name_plural': '10. Galeri Tambak'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Misi', 'verbose_name_plural': '5. Misi'},
        ),
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'verbose_name': 'Posisi Organisasi', 'verbose_name_plural': '8. Struktur Organisasi'},
        ),
        migrations.AlterModelOptions(
            name='pondstat',
            options={'verbose_name': 'Statistik Tambak', 'verbose_name_plural': '6. Statistik Tambak'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Pengaturan Situs', 'verbose_name_plural': '1. Pengaturan Situs'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='label',
            field=models.CharField(default='Tentang Kami', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='Opsional: tautan YouTube atau video profil', verbose_name='URL video'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama personel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#DDAA31', max_length=7, verbose_name='Warna emas'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_title',
            field=models.CharField(default='Mari Bertumbuh Bersama', max_length=100, verbose_name='Judul CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Deskripsi SEO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#075B37', help_text='Format HEX, contoh #075B37', max_length=7, verbose_name='Warna hijau utama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_text',
            field=models.CharField(default='Tonton Video', max_length=60, verbose_name='Teks tombol kedua'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#galeri', max_length=255, verbose_name='URL tombol kedua'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#043C27', max_length=7, verbose_name='Warna hijau gelap'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Gambar tentang kami'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Budidaya Modern, Berkelanjutan & Terpercaya', max_length=140),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, upload_to='facilities/', verbose_name='Gambar fasilitas'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=180, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='landing.organizationrole', verbose_name='Atasan'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='icon',
            field=models.CharField(blank=True, help_text='Nama Bootstrap Icons, contoh: shield-check, leaf, people', max_length=40, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Judul'),
        ),
        migrations.AlterField(
            model_name='pondstat',
            name='value',
            field=models.CharField(max_length=40, verbose_name='Nilai'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Muara Gembong, Kabupaten Bekasi', max_length=255, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Udang Emas Nusantara', max_length=120, verbose_name='Nama perusahaan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='Bersama kita wujudkan tambak Indonesia berkualitas dunia.', max_length=180, verbose_name='Deskripsi CTA'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge',
            field=models.CharField(default='Budidaya Udang Modern', max_length=80, verbose_name='Label hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default='Udang berkualitas tinggi melalui budidaya modern, teknologi tepat guna, dan pengelolaan profesional yang berkelanjutan.', verbose_name='Deskripsi hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Gambar utama/hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_highlight',
            field=models.CharField(default='Kualitas Dunia', max_length=80, verbose_name='Teks sorotan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_line_1',
            field=models.CharField(default='Dari Tambak Nusantara untuk', max_length=120, verbose_name='Judul hero'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branding/', verbose_name='Logo udang tanpa tulisan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_text',
            field=models.CharField(default='Kenali Kami Lebih Dekat', max_length=60, verbose_name='Teks tombol utama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_url',
            field=models.CharField(default='#tentang', max_length=255, verbose_name='URL tombol utama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Dari Tambak Nusantara untuk Kualitas Dunia', max_length=180, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Contoh: 6281234567890', max_length=30, verbose_name='Nomor WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
